name: "📚 Report a documentation issue"
description: "Missing information in our docs? Report a documentation issue"
title: "📚 "
type: documentation
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Describe the inconsistency or issue you found in [our documentation](https://godot-mobile-plugins.github.io/godot-oauth2/)
        or indicate where improvement is needed. Explain the severity and impact.
    validations:
      required: true

  - type: textarea
    id: related-links
    attributes:
      label: Related links
      description: >-
        List links to affected sections of [our documentation](https://godot-mobile-plugins.github.io/godot-oauth2/),
        screenshots if needed, and optionally related open or closed [issues](https://github.com/godot-mobile-plugins/godot-oauth2/issues).
    validations:
      required: true

  - type: textarea
    id: proposed-change
    attributes:
      label: Proposed change
      description: >-
        Optional: Suggest improvements or changes to the documentation.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your report fulfills the following:
      options:
        - label: I have reviewed the documentation guidelines.
          required: true
        - label: I have attached links or screenshots for affected sections.
          required: true